### ISSUE TITLE
App Store Deployment (After Step 2.7-Final Step in the LIKHA-Guide on Section 2) 

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#15]
Salut! I have successfully uploaded my archived app onto iTunes. Does this mean that the app is already in review? When I checked iTunes Connect, the app info is still saying `1.0 Prepare for submission`. Merci beaucoup!

**Comment by chrisamanse** [comment]
No, archiving simply means it's already packaged for release, and it can be uploaded to iTunes Connect. The final step in App Store Deployment, step 7, mentions "Choose Upload to App Store" (The button can be seen on the right side of the screenshot).

**Comment by chrisamanse** [comment]
No, archiving simply means it's already packaged for release, and it can be
uploaded to iTunes Connect. The final step in App Store Deployment, step 7,
mentions "Choose Upload to App Store" (The button can be seen on the right
side of the screenshot).

On Oct 26, 2016, at 01:03, Masarap Mabuhay notifications@github.com wrote:

Salut! I have successfully uploaded my archived app onto iTunes. Does this
mean that the app is already in review? When I checked iTunes Connect, the
app info is still saying 1.0 Prepare for submission. Merci beaucoup!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/usbong/LIKHA-Guide/issues/15, or mute the thread

**Comment by masarapmabuhay** [comment]
Salut! I have also successfully uploaded the archive onto the App Store. It seemed like my previous uploads failed to complete. Having said this, the app is still not in iTunes Connect. The section on `iOS App` is still saying: "1.0 Prepare for Submission". Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Bonnes nouvelles! As it turns out, I had to wait for iTunes Connect to send me an email saying that it has completed processing the app. I've already downloaded and installed the TestFlight app, and have sent myself an invite to do beta testing via iTunes Connect. I am already able to do testing. Merci beaucoup!

**Comment by chrisamanse** [comment]
Yes, after uploading to iTunes Connect, you would have to go to the iTunes Connect website and manually submit the app for review or use TestFlight (after iTunes Connect completes processing the build).

**Comment by masarapmabuhay** [comment]
D'accord! Merci encore une fois!
