### ISSUE TITLE
Iconizer -> AppIcon

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#2]
I've generated my app's icons using Iconizer. Is there a way to automatically import all of them to Assets.xcassets as AppIcon? Or would I need to manually drag and drop them to the AppIcon (App Icon Set) panel?

**Comment by chrisamanse** [comment]
The `AppIcon`'s folder location is on `LIKHA/Assets.xcassets/AppIcon.appiconset`. You can replace this folder manually in Finder with folder generated by **Iconizer**. In **Iconizer**, you also need to check _Export as Combined Asset_, so that app icons for both iPhone and iPad are inside the `.appiconset` folder.

Step-by-step screenshots:
1. ![1](https://cloud.githubusercontent.com/assets/12277586/18944026/9271416a-8655-11e6-9122-e3b13c17e070.png)
2. ![2](https://cloud.githubusercontent.com/assets/12277586/18944030/9f1fb87e-8655-11e6-9bca-519fcff9d918.png)
3. ![3](https://cloud.githubusercontent.com/assets/12277586/18944064/ce7cf992-8655-11e6-8850-06ee44323d83.png)
4. ![4](https://cloud.githubusercontent.com/assets/12277586/18944072/d47faede-8655-11e6-9531-2bd22a4a7aab.png)
5. ![5](https://cloud.githubusercontent.com/assets/12277586/18944054/bf5805ce-8655-11e6-96c9-7245f2b661de.png)

**Comment by masarapmabuhay** [comment]
Thank you for the reply.

After doing the steps that you gave, I noticed that there are superfluous icons related to car, mac, and watch, which I no longer included when I copy-pasted the generated icons onto the AppIcon.appiconset folder. 

Is there a way such that these unnecessary icons would not be generated anymore?

Also, I am missing an icon: ipadpro-appicon@2x.png.
Iconizer did not seem to have generated this.

**Comment by chrisamanse** [comment]
> Is there a way such that these unnecessary icons would not be generated anymore?

As shown in the screenshot above for 1, only the iPhone and iPad checkboxes should be checked since only App Icons for iPhone and iPad are needed (there are no watchOS, macOS or Car Play apps for LIKHA).

> Also, I am missing an icon: `ipadpro-appicon@2x.png`.
> Iconizer did not seem to have generated this.

I've had this issue once. Are you using the _latest version_ of Iconizer? If not, try using Iconizer version 2.2 and above. If it's already the latest version, this may be a bug of [Iconizer](https://github.com/raphaelhanneken/Iconizer). Try using [version 2.2](https://github.com/raphaelhanneken/iconizer/releases/tag/2.2) of Iconizer, which is where the support for iPad Pro icons initially added.

If this still hasn't resolved the issue, manually resize the original 1024x1024 px app icon to 167x167 px, and drag-and-drop it to the iPad Pro app icon slot in Xcode.

**Comment by masarapmabuhay** [comment]
Thank you for the reply.

OK. I missed those checkboxes there in screenshot 1. 
Thanks for pointing that out.

I'm using version 2.2 (the one before the latest). Let me see if I can tinker with it some more. If it's still no good, I'll likely just resize the original 1024x1024px app icon to 167x167.
