### ISSUE TITLE
Is the cover Image really 650x800?

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#3]
Is the cover image really 650x800px (based on the sample image that came along upon downloading LIKHA)?

What if it's a square? For example, 650x650? Should the remaining pixels be made transparent to reach 800px?

**Comment by chrisamanse** [comment]
The cover image can be any size. When the app runs, it automatically resizes it to fit it to the width of the screen while maintaining its aspect ratio.

This is the function used to compute the image dimensions (specifically, only the height gets programmatically computed since the width is set to always be equal to the screen width): https://github.com/usbong/LIKHA/blob/master/LIKHA/ViewController.swift#L40-L49

> What if it's a square? For example, 650x650? Should the remaining pixels be made transparent to reach 800px?

If the cover image supplied is a square, the cover image will also be a square. If the remaining pixels are made transparent to reach 800px, the "START" button will then be further below the cover image, since the button position is set to be just below the cover image.

**Comment by masarapmabuhay** [comment]
Excellent! Merci beaucoup!
