### ISSUE TITLE
For step 5,  I had to add Simulators first

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#4]
In step 5, I had to add Simulators first.

Which simulator do you generally use for testing?
I don't necessarily have to test my app on all the simulators, right?

**Comment by chrisamanse** [comment]
> Which simulator do you generally use for testing?

Traditionally, the latest iOS device (which is currently the iPhone 7 or iPhone 7 Plus) is the one used for simulation. But since I don't have a Retina/High resolution screen, the iPhone 6 and later devices is too big for my screen, so I use the iPhone 5. Although, it is possible to scale down the simulator, which is useful for iPad simulators, via the `Window > Scale` options found in the Menu bar in the Simulator app.

> I don't necessarily have to test my app on all the simulators, right?

It's good practice to test the app on other simulators to see how the app behaves in different screen sizes. However, since [UsbongKit](https://github.com/usbong/UsbongKit) mostly uses scroll views, any objects that go beyond the bounds of the screen can be viewed by simply scrolling the current view. This is also applicable to the Start page of the app, such that when a cover image is a very long image, the page is scrollable, and the Start button can be viewed by further scrolling down.

**Comment by masarapmabuhay** [comment]
D'accord! Merci beaucoup!
