### ISSUE TITLE
Run App -> Warnings and Errors 

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#5]
After going through the steps in the guide until step 5, and pressing Run, I encountered the following Warnings and Errors.

<img width="257" alt="screen shot 2016-09-30 at 8 36 34 am" src="https://cloud.githubusercontent.com/assets/344066/18977072/0567be6c-86ea-11e6-8a5e-19737c02c529.png">
<img width="254" alt="screen shot 2016-09-30 at 8 37 08 am" src="https://cloud.githubusercontent.com/assets/344066/18977075/087a033a-86ea-11e6-90fe-8841f286de46.png">
<img width="260" alt="screen shot 2016-09-30 at 8 38 19 am" src="https://cloud.githubusercontent.com/assets/344066/18977081/0dae2476-86ea-11e6-96eb-a26803fd69ad.png">

**Comment by chrisamanse** [comment]
1. What version of Xcode are you using? _LIKHA needs Xcode 7.3.1 to run without further modifications._
2. Also, did you manually resize the App Icon images? It looks like that all the App icon images has twice the required dimensions. _Try generating a new set of images using [Iconizer](https://github.com/raphaelhanneken/Iconizer)._

**Comment by masarapmabuhay** [comment]
1. I am using Xcode 8. I hope there's a way to resolve this. In the meantime, I'll be tinkering with Xcode and see what I can do.
2. I only manually resized 1, i.e. ipadpro-appicon@2x.png (167x167).
   --> I ran Iconizer again, and regenerated the images.
   --> I transferred the images into the AppIcon folder (outside Xcode).
   Et voilà! As it turns out, Xcode didn't seem to have refreshed. I closed Assets.xcassets, and reopened it. The Warnings related to the AppIcons have been resolved.

Merci bien!

**Comment by chrisamanse** [comment]
1. In order to use LIKHA with Xcode 8, LIKHA and all of its dependencies should be updated to Swift 2.3 or Swift 3.0. This is because Xcode 8 is using a newer compiler than Xcode 7.
   
   You can download Xcode 7 [here](https://developer.apple.com/download/more/) from Apple. You'll need to be signed in with your registered developer account to access the link. After extracting the download, make sure to rename the extracted app from "Xcode" to "Xcode 7", and move it to `/Applications` folder, to differentiate it from your current Xcode, which is in version 8.

**Comment by masarapmabuhay** [comment]
Yes, I updated Swift in Xcode 8 to 2.3, and got a bunch of Warnings and Errors.

I'll download Xcode 7, and see how far I can move from there.
In the meantime, thank you.

Merci beaucoup!
