### ISSUE TITLE
How to rename Xcode 7.3.1 after extraction

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#7]
I've successfully downloaded Xcode 7.3.1, and have opened it (to extract). I then see the following screen. 
<img width="607" alt="screen shot 2016-10-01 at 6 17 31 pm" src="https://cloud.githubusercontent.com/assets/344066/19013442/7d7455ea-8803-11e6-87b1-7dd24cffe9b8.png">

Being a somewhat noob with Macs, how do I rename "Xcode" to another name, e.g. "Xcode 7", so that it is differentiated with my Xcode 8?

Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Somehow, after transferring Xcode to Applications, OSX created a new Xcode, but named as "Xcode 2". This then differentiates my Xcode 7 with Xcode 8. I wonder if there is a way to rename Xcode, before transferring to Applications. If there's none, then I'm fine with renaming my "Xcode 2" to "Xcode 7" after transferring it to Applications.

**Comment by chrisamanse** [comment]
Yes, you'd have to drag it to the Applications folder first before renaming since `Xcode.dmg` is read-only, which means you cannot edit the files inside it.

The steps you did are correct: drag first to Applications (while making sure to not overwrite the other Xcode in the Application folder), then rename. You can now run Xcode 7. Do note that only one of them can run at the same time (You can't run Xcode 7 and Xcode 8 simultaneously).

**Comment by masarapmabuhay** [comment]
D'accord! Merci beaucoup encore une fois!
